#!/usr/bin/env bash

# This is a sample configuration file for safe-rm.
# By default, you could copy this file to ~/.safe-rm/config

#
# If you want to use a trash directory other than the default system trash,
#   uncomment the line after divider `-----`
#   and set the path to the desired trash directory.
# By default, safe-rm will use the system trash.
# -----------------------------------------------
# export SAFE_RM_TRASH=/path/to/trash

#
# (Linux only) If you want deletes across filesystems/mounts to stay instant,
#   uncomment the line after divider `-----` to keep a trash directory per
#   mount (following the FreeDesktop trash spec) instead of always moving files
#   into the home trash.
# It defaults to 'no'. Any value starting with 'y' or 'Y' is treated as 'yes'.
# Note: it only applies when using the default trash; setting a custom
#   SAFE_RM_TRASH above disables it.
# -----------------------------------------------
# export SAFE_RM_TRASH_PER_MOUNT=yes

#
# If you want to permanently delete files that are already in the trash,
#   uncomment the line after divider `-----`
# It defaults to 'no'.
# Pay attention that any value that starts with 'y' or 'Y' will be treated as 'yes'.
# -----------------------------------------------
# export SAFE_RM_PERM_DEL_FILES_IN_TRASH=yes

#
# If you want to disable the use of AppleScript for moving files to the trash,
#   uncomment the line after divider `-----`
# It defaults to 'yes'.
# By setting it to 'no', the "put-back" feature will be disabled for MacOS.
# -----------------------------------------------
# export SAFE_RM_USE_APPLESCRIPT=no

#
# If you want to change the configuration root directory of safe-rm, in order to
#   - put the .gitignore file in a different directory other than `~/.safe-rm/`
# Uncomment the line after divider `-----`
# -----------------------------------------------
# export SAFE_RM_CONFIG_ROOT=/usr/local/etc/safe-rm
